name: build tezpay 

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.3'
      - name: Test
        run: go test -v ./...
      - name: Build win-arm64
        run: env GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o bin/tezpay-win-arm64.exe
      - name: Build win-amd64
        run: env GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o bin/tezpay-win-amd64.exe
      - name: Build linux-arm64
        run: env GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o bin/tezpay-linux-arm64
      - name: Build linux-amd64
        run: env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/tezpay-linux-amd64
      - name: Build macos-arm64
        run: env GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o bin/tezpay-macos-arm64
      - name: Build macos-amd64
        run: env GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o bin/tezpay-macos-amd64

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file_glob: true
          file: bin/tezpay*