name: release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
      - name: Test
        run: go test -v ./...
      - name: Build win-arm64
        run: env GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o bin/tezpay-win-arm64.exe
      - name: Build win-amd64
        run: env GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o bin/tezpay-win-amd64.exe
      - name: Build linux-arm64
        run: env GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o bin/tezpay-linux-arm64
      - name: Build linux-amd64
        run: env GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/tezpay-linux-amd64
      - name: Build macos-arm64
        run: env GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o bin/tezpay-macos-arm64
      - name: Build macos-amd64
        run: env GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o bin/tezpay-macos-amd64

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.4.0
        with:
          # repo_token: ${{ secrets.GITHUB_TOKEN }}
          # tag: ${{ github.ref }}
          file_glob: true
          file: bin/tezpay*

      - name: Ami Tezpay Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.AMI_TEZPAY_ACCESS_TOKEN }}
          repository: tez-capital/ami-tezpay
          event-type: tezpay-release
          client-payload: '{ "id": "${{ steps.repository_info.outputs.ID }}", "repository": "${{github.repository}}", "version": "${{github.ref_name}}" }'

      - name: Notify new version available
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.PB_DISCORD_WEBHOOK }}
        with:
            args: "New tezpay ${{ github.ref_name }} released. (<https://github.com/tez-capital/tezpay/releases/tag/${{ github.ref_name }}>)"
